plugins {
    id 'java'
    id 'war'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'

}

group = 'dayp308'
version = '0.0.1-SNAPSHOT'
def hibernateVersion = '6.6.7.Final'
def lombokVersion = '1.18.36'
def mapstructVersion = '1.6.3'
def mapstructSpringExtensionsVersion = '1.1.2'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.session:spring-session-core'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation "org.springframework.boot:spring-boot-starter-security"
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-gradle-plugin:3.4.3'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2'

	// https://mvnrepository.com/artifact/commons-codec/commons-codec
	implementation group: 'commons-codec', name: 'commons-codec', version: '1.17.0'
    implementation group: 'commons-io', name: 'commons-io', version: '2.16.1'
	// https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
	implementation group: 'org.apache.commons', name: 'commons-collections4', version: '4.5.0-M2'

	// https://mvnrepository.com/artifact/org.apache.tomcat.embed/tomcat-embed-jasper
	providedRuntime group: 'org.apache.tomcat.embed', name: 'tomcat-embed-jasper', version: '10.1.24'
	// https://mvnrepository.com/artifact/jakarta.servlet.jsp.jstl/jakarta.servlet.jsp.jstl-api
	implementation group: 'jakarta.servlet.jsp.jstl', name: 'jakarta.servlet.jsp.jstl-api', version: '3.0.0'
    // https://mvnrepository.com/artifact/jakarta.servlet.jsp/jakarta.servlet.jsp-api
    compileOnly group: 'jakarta.servlet.jsp', name: 'jakarta.servlet.jsp-api', version: '3.1.1'
    // https://mvnrepository.com/artifact/org.glassfish.web/jakarta.servlet.jsp.jstl
    implementation group: 'org.glassfish.web', name: 'jakarta.servlet.jsp.jstl', version: '3.0.1'
    // https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-core
    implementation group: 'org.hibernate.orm', name: 'hibernate-core', version: hibernateVersion
// https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-hikaricp
    implementation group: 'org.hibernate.orm', name: 'hibernate-hikaricp', version: hibernateVersion
    // https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-jpamodelgen
    compileOnly group: 'org.hibernate.orm', name: 'hibernate-jpamodelgen', version: hibernateVersion
    annotationProcessor group: 'org.hibernate.orm', name: 'hibernate-jpamodelgen', version: hibernateVersion
    testCompileOnly group: 'org.hibernate.orm', name: 'hibernate-jpamodelgen', version: hibernateVersion
    testAnnotationProcessor group: 'org.hibernate.orm', name: 'hibernate-jpamodelgen', version: hibernateVersion


    // https://mvnrepository.com/artifact/org.projectlombok/lombok
    compileOnly group: 'org.projectlombok', name: 'lombok', version: lombokVersion
    annotationProcessor group: 'org.projectlombok', name: 'lombok', version: lombokVersion
    testCompileOnly group: 'org.projectlombok', name: 'lombok', version: lombokVersion
    testAnnotationProcessor group: 'org.projectlombok', name: 'lombok', version: lombokVersion


    implementation group: 'org.mapstruct', name: 'mapstruct', version: mapstructVersion
    annotationProcessor group: 'org.mapstruct', name: 'mapstruct-processor', version: mapstructVersion

    implementation "org.mapstruct.extensions.spring:mapstruct-spring-annotations:${mapstructSpringExtensionsVersion}"
    annotationProcessor "org.mapstruct.extensions.spring:mapstruct-spring-extensions:${mapstructSpringExtensionsVersion}"

    testAnnotationProcessor "org.mapstruct.extensions.spring:mapstruct-spring-extensions:${mapstructSpringExtensionsVersion}"
    testImplementation "org.mapstruct.extensions.spring:mapstruct-spring-test-extensions:${mapstructSpringExtensionsVersion}"

    // https://mvnrepository.com/artifact/commons-validator/commons-validator
    implementation group: 'commons-validator', name: 'commons-validator', version: '1.9.0'
    // https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.17.0'



}
sourceSets {
}

compileJava {
    options.generatedSourceOutputDirectory = file('src/generated')

}

tasks.named('test') {
    useJUnitPlatform()
}

ext {
    staticDir = './src/main/webapp/static'
    viteDir = './vite'
    nodeJsOutDir = './src/main/resources/static/dist'
}

tasks.register('compileScss') {
    inputs.dir staticDir
    def tree = fileTree(staticDir + "/scss") {
        exclude("module", ".sass-cache")
    }
    tree.each {
        File scssFile ->
            exec {
                workingDir(staticDir)
                commandLine 'sass', "scss/${scssFile.name}", "css/${scssFile.name.replaceFirst(~/\.[^.]+$/, '.css')}"
            }
    }
}

tasks.register('compileJs') {
    inputs.dir nodeJsDir
    exec {
        workingDir(nodeJsDir)
        commandLine 'yarn', 'build'
    }
}

bootJar {
    exclude('**/application.properties')
}

test {
    testLogging.showStandardStreams true
}
