spring:
  main:
    web-application-type: servlet
  application:
    name: 'chat_springboot'
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: 'jdbc:mariadb://localhost:3306/lebabel?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false'
    username: 'lebabel'
    password: '123456'
    hikari:
      driver-class-name: 'org.mariadb.jdbc.Driver'
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'
  servlet:
    multipart:
      max-file-size: 64MB
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/dist/
        - classpath:/public/
#        - file:${dayp308.chatroom.fileStorePath}
#        - file:${dayp308.chatroom.assetsPath}
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          fetch_size: 1048576
  jackson:
    serialization:
      write-dates-as-timestamps: true
    deserialization:
      read-unknown-enum-values-using-default-value: true

#mybatis:
#  type-aliases-package: 'dayp308.chatroom.bean'
#  mapper-locations: 'classpath*:dayp308/chatroom/mapper/*.xml'
#  configuration:
#    map-underscore-to-camel-case: true
#    lazy-loading-enabled: true
#  type-handlers-package: 'dayp308.chatroom.typehandler'
