dayp308.chatroom.fileStorePath=/home/dayp308/.local/share/chatroom/uploadFiles/
dayp308.chatroom.assetsPath=/home/dayp308/.local/share/chatroom/assets
dayp308.chatroom.imgPath = /home/dayp308/.local/share/chatroom/images
dayp308.chatroom.thumbnailPath = thumbnail
dayp308.chatroom.viteAddress = "http://vite:5173"

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
