spring:
  main:
    web-application-type: servlet
  application:
    name: 'chat_springboot'
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lebabel}?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: ${DB_USER:lebabel}
    password: ${DB_PASSWORD:123456}
    hikari:
      driver-class-name: 'org.mariadb.jdbc.Driver'
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'
  servlet:
    multipart:
      max-file-size: 64MB
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/dist/
        - classpath:/public/
        # - file:${dayp308.chatroom.fileStorePath}
        # - file:${dayp308.chatroom.assetsPath}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          fetch_size: 1048576
  jackson:
    serialization:
      write-dates-as-timestamps: true
    deserialization:
      read-unknown-enum-values-using-default-value: true
lebabel:
  img-path: ${IMG_PATH}
  vite-host: ${VITE_HOST:http://localhost:5173}
