spring:
  application:
    name: 'chat_springboot'
  datasource:
    url: 'jdbc:mariadb://localhost:3306/chatroom?user=root&password=123456&&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false'
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'
  servlet:
    multipart:
      max-file-size: 128MB
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - file:${dayp308.chatroom.fileStorePath}
        - file:${dayp308.chatroom.resourcePath}

mybatis:
  type-aliases-package: 'dayp308.chatroom.bean'
  mapper-locations: 'classpath*:dayp308/chatroom/mapper/*.xml'
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
  type-handlers-package: 'dayp308.chatroom.typehandler'
