lebabel.img-path=/home/dayp308/.local/share/lebabel/images/

spring.jpa.show-sql=false
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
logging.level.web=debug
debug=true
